DELETE http://localhost:6000/api/projects/68e8b8800fb7c555bc25a53a
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGU4OWNhMDBlNzRkZTI5MTk0ZmQ5NzIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwMDgxODIwLCJleHAiOjE3NjAxNjgyMjB9.3346OjmNfrqC1re7YqIbURrqCaVdU_MdPbxCJPuNVMk



DELETE http://localhost:6000/api/blogs/68e8a80277e43dda65f84f1c
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGU4OWNhMDBlNzRkZTI5MTk0ZmQ5NzIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwMDc3ODA1LCJleHAiOjE3NjAxNjQyMDV9.8ikOCMQ0yWEZShNORj4_lyHwyf7T5n_G_97D-kTBOh8
