GET http://localhost:6000/api/projects


GET http://localhost:6000/api/projects/68e7ecb6db3e8ff0f6292ff1NP


GET http://localhost:6000/api/blogs


GET http://localhost:6000/api/blogs/68e80c514b9a0b1af3c9494b