POST http://localhost:4000/api/project
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGU4OWNhMDBlNzRkZTI5MTk0ZmQ5NzIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwMDgxODIwLCJleHAiOjE3NjAxNjgyMjB9.3346OjmNfrqC1re7YqIbURrqCaVdU_MdPbxCJPuNVMk

{
  "title": "ShopMate",
  "description": "A movie search web app using TMDB API.",
  "technologies": ["React", "Tailwind CSS", "API"],
  "image": "https://cinemate-movie-dg.netlify.app/preview.png",
  "githubLink": "https://github.com/yourname/cinemate",
  "liveLink": "https://cinemate-movie-dg.netlify.app/"
}



POST http://localhost:6000/api/blogs
Content-Type:application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGU4OWNhMDBlNzRkZTI5MTk0ZmQ5NzIiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaWF0IjoxNzYwMDc3ODA1LCJleHAiOjE3NjAxNjQyMDV9.8ikOCMQ0yWEZShNORj4_lyHwyf7T5n_G_97D-kTBOh8

{
  "title": "Building a CMS with Express Js",
  "content": "This blog explains how to build a CMS backend using Node.js and Express."
}
